par: par.o getLine.o inputTest.o checkBalance.o checkSpecial.o summarize.o 
	gcc -ansi -Wall -pedantic -g par.o getLine.o inputTest.o checkBalance.o checkSpecial.o summarize.o  -o par
par.o: par.c
	gcc -c -ansi -Wall -pedantic -g par.c -o par.o
inputTest.o: inputTest.c
	gcc -c -ansi -Wall -pedantic -g inputTest.c -o inputTest.o
getLine.o: getLine.c
	gcc -c -ansi -Wall -pedantic -g getLine.c -o getLine.o
checkBalance.o: checkBalance.c
	gcc -c -ansi -Wall -pedantic -g checkBalance.c -o checkBalance.o
checkSpecial.o: checkSpecial.c
	gcc -c -ansi -Wall -pedantic -g checkSpecial.c -o checkSpecial.o
summarize.o: summarize.c
	gcc -c -ansi -Wall -pedantic -g summarize.c -o summarize.o
